# Site settings
title: Archon | Lair
SEOTitle: Archon | Lair
header-img: img/header.jpg
email: qq349074225@live.com
description: ""
keyword: ""
url: "https://github.com/archongum"
baseurl: ""

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
github_username:    archongum
stackoverflow_username:     9756912/archon
docker_username:    dockergum
csdn_username:      c13232906050 
# weibo_username:     ArchonGum
# zhihu_username:     alexgum
# twitter_username:   archongum
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: archongum

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
ba_track_id: 9924571e27fcaad8611ab32ee5b91fec

# Google Analytics
ga_track_id: 
ga_domain: 



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Live and let live"
sidebar-avatar: /img/user-avatar.jpg



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
        title: "CSDN",
        href: "https://blog.csdn.net/c13232906050"
    },
    {
        title: "Stack Overflow",
        href: "https://stackoverflow.com/users/9756912/archon"
    },
    {
        title: "DockerGum",
        href: "https://cloud.docker.com/u/dockergum"
    }
]
